name: fe-monorepo

services:
  pg:
    image: postgres:latest
    environment:
      POSTGRES_DB: pg
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
    # From another Compose service: postgres://pg:pg@pg:5432/pg
    # From the host: use localhost:5442 (host port below)
    ports:
      - "5442:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    restart: always

  otel-lgtm:
    image: docker.io/grafana/otel-lgtm:latest
    ports:
      - "3111:3000" # Grafana UI
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    volumes:
      - ./otel-lgtm/grafana:/data/grafana
      - ./otel-lgtm/prometheus:/data/prometheus
      - ./otel-lgtm/loki:/data/loki
    environment:
      - GF_PATHS_DATA=/data/grafana
    env_file:
      - ./.env
    # stdin_open: true
    # tty: true

volumes:
  pg_data:
